name: TG-SquidGame
version: 1.0
main: org.tg.squidgame.TGSquidGame
api-version: 1.21
author: Techinpoint Gamerz
description: Modular Squid Game plugin with multiple arenas

commands:
  tgsg:
    description: Main TG SquidGame command
    usage: /tgsg <subcommand>
    aliases: [sg]
