name: TG-SquidGame
version: 1.2
main: org.tg.squidgame.TGSquidGame
api-version: "1.21"
author: Techinpoint Gamerz
description: Professional Squid Game plugin with multiple arenas for Paper 1.21.1+

commands:
  tgsg:
    description: Main TG SquidGame command
    usage: /tgsg <subcommand>
    aliases: [sg, SquidGame]

permissions:
  tgsg.*:
    description: Gives access to all TG SquidGame commands
    default: op
    children:
      tgsg.admin: true
      tgsg.user: true
  
  tgsg.admin:
    description: Allows admin commands (create, edit, delete, configure arenas)
    default: op
  
  tgsg.user:
    description: Allows user commands (join arena, view list)
    default: true
